# Generated by Django 5.0.3 on 2024-03-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedProfile',
            fields=[
                ('profile_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('substancia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('laboratorio', models.CharField(max_length=255)),
                ('codigo_ggrem', models.CharField(max_length=20)),
                ('registro', models.CharField(max_length=20)),
                ('ean_1', models.CharField(max_length=20)),
                ('ean_2', models.CharField(max_length=20)),
                ('ean_3', models.CharField(max_length=20)),
                ('produto', models.CharField(max_length=255)),
                ('apresentacao', models.CharField(max_length=255)),
                ('classe_terapeutica', models.CharField(max_length=255)),
                ('tipo_de_produto', models.CharField(max_length=255)),
                ('regime_de_preco', models.CharField(max_length=255)),
                ('pf_sem_imposto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pf_0', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_12', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_12_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_17', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_17_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_17_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_17_5_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_18', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_18_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_19', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_19_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_19_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_19_5_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_20', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_20_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_20_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_21', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_21_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_22', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_22_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmvg_sem_imposto', models.CharField(default='', max_length=10)),
                ('pmvg_0', models.CharField(default='', max_length=10)),
                ('pmvg_12', models.CharField(default='', max_length=10)),
                ('pmvg_12_alc', models.CharField(default='', max_length=10)),
                ('pmvg_17', models.CharField(default='', max_length=10)),
                ('pmvg_17_alc', models.CharField(default='', max_length=10)),
                ('pmvg_17_5', models.CharField(default='', max_length=10)),
                ('pmvg_17_5_alc', models.CharField(default='', max_length=10)),
                ('pmvg_18', models.CharField(default='', max_length=10)),
                ('pmvg_18_alc', models.CharField(default='', max_length=10)),
                ('pmvg_19', models.CharField(default='', max_length=10)),
                ('pmvg_19_alc', models.CharField(default='', max_length=10)),
                ('pmvg_19_5', models.CharField(default='', max_length=10)),
                ('pmvg_19_5_alc', models.CharField(default='', max_length=10)),
                ('pmvg_20', models.CharField(default='', max_length=10)),
                ('pmvg_20_alc', models.CharField(default='', max_length=10)),
                ('pmvg_20_5', models.CharField(default='', max_length=10)),
                ('pmvg_21', models.CharField(default='', max_length=10)),
                ('pmvg_21_alc', models.CharField(default='', max_length=10)),
                ('pmvg_22', models.CharField(default='', max_length=10)),
                ('pmvg_22_alc', models.CharField(default='', max_length=10)),
                ('restricao_hospitalar', models.CharField(default='', max_length=50)),
                ('cap', models.CharField(default='', max_length=50)),
                ('confaz_87', models.CharField(default='', max_length=50)),
                ('icms_0', models.CharField(default='', max_length=50)),
                ('analise_recursal', models.CharField(max_length=50, null=True)),
                ('lista_conc_cred_trib', models.CharField(default='', max_length=50)),
                ('comercializacao_2022', models.CharField(default='', max_length=50)),
                ('tarja', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
