# Generated by Django 5.0.3 on 2024-03-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchmeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medprofile',
            name='apresentacao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='cap',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='classe_terapeutica',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='cnpj',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='codigo_ggrem',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='confaz_87',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='ean_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='ean_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='ean_3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='icms_0',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='laboratorio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_0',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_12',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_12_alc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_17',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_17_5',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_17_5_alc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_17_alc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_18',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_18_alc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_19',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_19_5',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_19_5_alc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_19_alc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_20',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_20_5',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_20_alc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_21',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_21_alc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_22',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_22_alc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_sem_imposto',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_0',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_12',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_12_alc',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_17',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_17_5',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_17_5_alc',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_17_alc',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_18',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_18_alc',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_19',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_19_5',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_19_5_alc',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_19_alc',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_20',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_20_5',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_20_alc',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_21',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_21_alc',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_22',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_22_alc',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pmvg_sem_imposto',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='produto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='regime_de_preco',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='registro',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='restricao_hospitalar',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='substancia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='tipo_de_produto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
