# Generated by Django 5.0.3 on 2024-03-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchmeds', '0003_alter_medprofile_apresentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medprofile',
            name='pf_0',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_12',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_12_alc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_17',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_17_5',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_17_5_alc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_17_alc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_18',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_18_alc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_19',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_19_5',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_19_5_alc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_19_alc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_20',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_20_5',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_20_alc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_21',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_21_alc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_22',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='medprofile',
            name='pf_22_alc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
